#in this file i am going to make a form like all the basic information of any student use for the
# any job/admission/etc
print("---------------welcom to the student's information entry desk-------------------")
print("---------------Please!, Carefully enter the information-------------------------")
stuname=str(input('Name: '))
fname=str(input('Enter Father name: '))
mname=str(input('Enter Mother name: '))
city=str(input('Enter City name: '))
country=str(input('Enter country name: '))
addr=input('Permanant adress:')
pho=int(input('Enter active Mobile/telephone number:'))
cn=int(input("Enter CNIC number:"))
b=input("Blood group:")
weight=float(input('Body weight:'))
mail=input("Enter Email-adress:")
cast=str(input("Enter Cast:"))
r=str(input("Religion:"))
s=int(input("How many Siblings:"))
sta=str(input('Status(married/single/widow):'))
g=str(input('Gender:'))
l=str(input("National Language:"))
print("---------THANK YOU!!-------")
print("--------------------------------------------------------------------------------------------")

print('================================================================================')
print('=                          STUDENT INFORMATION                                 =')
print('================================================================================')
print('=    NAME:',stuname),("FATHERNAME:",fname),("MOTHERNAME",mname)